### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username":"natalia",
  "email":"natalia@gmail.com",
  "password":"12345678"
}

### Authenticate
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "username":"natalia",
  "password":"12345678"
}



### Get user info
GET http://localhost:8080/account
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2YW55YSIsImlhdCI6MTY4NjQ3MDU3MSwiZXhwIjoxNjg2NDcyMzcxfQ.eD0829k_qcqLwtYWEinrf7aGPkD0htsKeTOqYe_QFok

### Update user
PUT http://localhost:8080/account
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYXRhbGlhIiwiaWF0IjoxNjg2NTA1NDgxLCJleHAiOjE2ODY1MDcyODF9.HV5OQWoXpZ11CJalO0PmhlO_9Y_DpvTu5KvRuXGBBgw
Content-Type: application/json

{
  "email": "n@gmail.com",
  "password":"1234567810"
}


### Delete user
DELETE http://localhost:8080/account
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYXRhbGlhIiwiaWF0IjoxNjg2NTA1NDgxLCJleHAiOjE2ODY1MDcyODF9.HV5OQWoXpZ11CJalO0PmhlO_9Y_DpvTu5KvRuXGBBgw
