### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username":"ioann",
  "email":"ioann@gmail.com",
  "password":"12345678"
}

### Authenticate
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "username":"ioann",
  "password":"12345678"
}

###
GET http://localhost:8080/auth/getCurrentUserEmail?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpb2FubiIsImlhdCI6MTY4NjQxOTMwOCwiZXhwIjoxNjg2NDIxMTA4fQ.vse1UIqSYpWc9vzdK9M3AHPYeJWKPDyhp9AQHP8j27Y


###
GET http://localhost:9898/auth/getCurrentUserEmail?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpb2FubiIsImlhdCI6MTY4NjQxOTMwOCwiZXhwIjoxNjg2NDIxMTA4fQ.vse1UIqSYpWc9vzdK9M3AHPYeJWKPDyhp9AQHP8j27Y


###
GET http://localhost:8888/account/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpb2FubiIsImlhdCI6MTY4NjQxOTMwOCwiZXhwIjoxNjg2NDIxMTA4fQ.vse1UIqSYpWc9vzdK9M3AHPYeJWKPDyhp9AQHP8j27Y

###
GET http://localhost:8080/account/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpb2FubiIsImlhdCI6MTY4NjQxOTMwOCwiZXhwIjoxNjg2NDIxMTA4fQ.vse1UIqSYpWc9vzdK9M3AHPYeJWKPDyhp9AQHP8j27Y
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpb2FubiIsImlhdCI6MTY4NjQxOTMwOCwiZXhwIjoxNjg2NDIxMTA4fQ.vse1UIqSYpWc9vzdK9M3AHPYeJWKPDyhp9AQHP8j27Y
