POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstname":"sadfasd",
  "lastname":"asdfasdf",
  "email":"someex@yandex.ru",
  "password": "123sadfasdfasdf"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email":"someex@yandex.ru",
  "password": "1234"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}
###
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email":"someex@yandex.ru",
  "password": "123"
}
